// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFQt4VfkxRC9c0SPmSceY97fa9kr3t-bU',
    appId: '1:340402264096:ios:0560b22d213b9c37238445',
    messagingSenderId: '340402264096',
    projectId: 'hotes-app-3725e',
    storageBucket: 'hotes-app-3725e.firebasestorage.app',
    androidClientId: '340402264096-kr4o4uo2e3tip26glflj4u77o63bjouv.apps.googleusercontent.com',
    iosClientId: '340402264096-7e60v819gt2734auil1t490eqk3h4djb.apps.googleusercontent.com',
    iosBundleId: 'dev.khtt.hotes',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyAkatb35NSChSZxEOKQvT4ObZu4AdplA',
    appId: '1:340402264096:web:d495f6a96cfdcda2238445',
    messagingSenderId: '340402264096',
    projectId: 'hotes-app-3725e',
    authDomain: 'hotes-app-3725e.firebaseapp.com',
    storageBucket: 'hotes-app-3725e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFQt4VfkxRC9c0SPmSceY97fa9kr3t-bU',
    appId: '1:340402264096:ios:76c43b2109b208b3238445',
    messagingSenderId: '340402264096',
    projectId: 'hotes-app-3725e',
    storageBucket: 'hotes-app-3725e.firebasestorage.app',
    androidClientId: '340402264096-kr4o4uo2e3tip26glflj4u77o63bjouv.apps.googleusercontent.com',
    iosClientId: '340402264096-1klc3q4qm77q58176pabuf78hck1lnf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.hoteshinapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAveBtxxoWE_RqlnBxEpnA6HU36gezNhiw',
    appId: '1:340402264096:android:920c3cc5ec3084bc238445',
    messagingSenderId: '340402264096',
    projectId: 'hotes-app-3725e',
    storageBucket: 'hotes-app-3725e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyAkatb35NSChSZxEOKQvT4ObZu4AdplA',
    appId: '1:340402264096:web:23005ec803dc0900238445',
    messagingSenderId: '340402264096',
    projectId: 'hotes-app-3725e',
    authDomain: 'hotes-app-3725e.firebaseapp.com',
    storageBucket: 'hotes-app-3725e.firebasestorage.app',
  );

}