// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQHM7LhfozJAI2ECJYrmuJumFEhGHqOx4',
    appId: '1:704218210997:web:dca85b5ee9afd82b1614fc',
    messagingSenderId: '704218210997',
    projectId: 'authtutorial-10e55',
    authDomain: 'authtutorial-10e55.firebaseapp.com',
    storageBucket: 'authtutorial-10e55.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0sCQgyldlc4f1pFFnqSqPtcQb9BMUjfM',
    appId: '1:704218210997:android:9a5c010b33f7fd6d1614fc',
    messagingSenderId: '704218210997',
    projectId: 'authtutorial-10e55',
    storageBucket: 'authtutorial-10e55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8qi8OQfytm6G9JoIXQfTas5y5MCnybd0',
    appId: '1:704218210997:ios:182a19b2d46d94331614fc',
    messagingSenderId: '704218210997',
    projectId: 'authtutorial-10e55',
    storageBucket: 'authtutorial-10e55.firebasestorage.app',
    iosBundleId: 'com.example.googleauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8qi8OQfytm6G9JoIXQfTas5y5MCnybd0',
    appId: '1:704218210997:ios:182a19b2d46d94331614fc',
    messagingSenderId: '704218210997',
    projectId: 'authtutorial-10e55',
    storageBucket: 'authtutorial-10e55.firebasestorage.app',
    iosBundleId: 'com.example.googleauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQHM7LhfozJAI2ECJYrmuJumFEhGHqOx4',
    appId: '1:704218210997:web:7bced688b6cdd42f1614fc',
    messagingSenderId: '704218210997',
    projectId: 'authtutorial-10e55',
    authDomain: 'authtutorial-10e55.firebaseapp.com',
    storageBucket: 'authtutorial-10e55.firebasestorage.app',
  );
}
